# run with `docker-compose up -d`
# to unmount volume and reinitialize schema/data, run with `docker-compose down -v`
version: '3.5'

services:
    hebhisto:
        image: gcc
        working_dir: /app
        volumes:
            - .:/app
        container_name: heb-coding-challenge
        command: sh -c "
            make &&
            ./histogram input_files/input.txt &&
            make clean"
